import type { Contract, RiskAlert, KnowledgeDoc, CodeScanResult, TestCase, OASyncConfig, DashboardStats, AiExtractResult, ContractStage, RiskLevel } from '@/types';

// --- Contract Mock Data ---
const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString().slice(0, 10);
const daysLater = (d: number) => new Date(now.getTime() + d * 86400000).toISOString().slice(0, 10);

export const mockContracts: Contract[] = [
  {
    id: '1',
    code: 'HT-2024-001',
    partyA: '北京星辰科技有限公司',
    partyB: '上海月明信息系统有限公司',
    signDate: daysAgo(90),
    effectiveDate: daysAgo(80),
    expireDate: daysLater(280),
    dept: '销售部',
    handler: '张伟',
    amount: 1280000,
    subject: '智能监测系统采购及实施',
    unitPrice: 64000,
    taxRate: 13,
    paymentTerms: '合同签订后30日内付30%，验收合格后30日内付65%，质保金5%',
    deposit: 64000,
    deliverables: '设备交付、系统部署、操作培训',
    acceptanceStandard: 'GB/T 19001-2016 质量管理体系标准',
    servicePeriod: '12个月质保期',
    renewalConditions: '续约需提前60日书面通知，优先续约权',
    stage: 'S6_履约',
    status: 'active',
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },
  {
    id: '2',
    code: 'HT-2024-002',
    partyA: '深圳华腾数据集团',
    partyB: '上海月明信息系统有限公司',
    signDate: daysAgo(45),
    effectiveDate: daysLater(10),
    expireDate: daysLater(370),
    dept: '技术部',
    handler: '李娜',
    amount: 3560000,
    subject: '大数据平台运维服务',
    unitPrice: 890000,
    taxRate: 6,
    paymentTerms: '按季度付款，每季度末支付当季度服务费',
    deposit: 0,
    deliverables: '季度运维报告、月度巡检、故障响应',
    acceptanceStandard: 'SLA 99.5%可用性',
    servicePeriod: '24个月（可按年续约）',
    renewalConditions: '自动续约除非任何一方在到期前30日通知不续约',
    stage: 'S5_签订',
    status: 'active',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: '3',
    code: 'HT-2024-003',
    partyA: '杭州云帆电子商务有限公司',
    partyB: '上海月明信息系统有限公司',
    signDate: daysAgo(120),
    effectiveDate: daysAgo(110),
    expireDate: daysLater(30),
    dept: '客户二部',
    handler: '王磊',
    amount: 580000,
    subject: '在线客服系统升级',
    unitPrice: 29000,
    taxRate: 13,
    paymentTerms: '签约付50%，上线验收付50%',
    deposit: 0,
    deliverables: '客服系统升级、数据迁移、人员培训',
    acceptanceStandard: '功能测试通过率100%',
    servicePeriod: '6个月质保期',
    renewalConditions: '无自动续约条款',
    stage: 'S6_履约',
    status: 'risk',
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
  },
  {
    id: '4',
    code: 'HT-2024-004',
    partyA: '广州东方制造集团',
    partyB: '上海月明信息系统有限公司',
    signDate: daysLater(15),
    effectiveDate: daysLater(20),
    expireDate: daysLater(385),
    dept: '销售部',
    handler: '陈静',
    amount: 2100000,
    subject: 'MES制造执行系统定制开发',
    unitPrice: 1050000,
    taxRate: 13,
    paymentTerms: '签约付20%，需求确认付30%，上线验收付45%，质保金5%',
    deposit: 420000,
    deliverables: '需求分析、系统开发、部署上线、培训交付',
    acceptanceStandard: '功能性测试、性能压测、用户验收',
    servicePeriod: '12个月免费维护',
    renewalConditions: '后续功能扩展需签订补充协议',
    stage: 'S4_确认',
    status: 'pending',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: '5',
    code: 'HT-2023-089',
    partyA: '成都西部科创有限公司',
    partyB: '上海月明信息系统有限公司',
    signDate: daysAgo(400),
    effectiveDate: daysAgo(390),
    expireDate: daysAgo(20),
    dept: '技术部',
    handler: '赵强',
    amount: 920000,
    subject: '网络安全加固服务',
    unitPrice: 46000,
    taxRate: 6,
    paymentTerms: '签约付100%',
    deposit: 0,
    deliverables: '安全评估报告、加固方案、渗透测试',
    acceptanceStandard: '等保2.0三级合规',
    servicePeriod: '合同履行完毕',
    renewalConditions: '无续约条款',
    stage: 'completed',
    status: 'completed',
    createdAt: daysAgo(400),
    updatedAt: daysAgo(20),
  },
];

export const mockRiskAlerts: RiskAlert[] = [
  {
    id: 'ra-1',
    contractId: '3',
    contractCode: 'HT-2024-003',
    level: 'high',
    type: '到期预警',
    content: '合同将于30天内到期，需安排续约或交接',
    suggestion: '联系客户确认续约意愿，启动交接准备',
    historyRef: 'HT-2023-089 到期前未及时交接导致服务空档',
    createdAt: daysAgo(1),
    resolved: false,
  },
  {
    id: 'ra-2',
    contractId: '1',
    contractCode: 'HT-2024-001',
    level: 'medium',
    type: '付款提醒',
    content: '本期巡检报告已提交30天，对应付款节点将到',
    suggestion: '确认验收状态并启动付款流程',
    historyRef: 'HT-2024-001 首次付款延迟14天',
    createdAt: daysAgo(3),
    resolved: false,
  },
  {
    id: 'ra-3',
    contractId: '2',
    contractCode: 'HT-2024-002',
    level: 'low',
    type: '服务提醒',
    content: '距下次月度巡检还有7天',
    suggestion: '安排巡检人员与客户对接',
    historyRef: '',
    createdAt: daysAgo(1),
    resolved: false,
  },
];

export const mockAiExtract: AiExtractResult = {
  id: 'ae-1',
  fields: [
    { field: '合同编号', value: 'HT-2024-DEMO', confidence: 0.95 },
    { field: '甲方名称', value: '示例甲方科技有限公司', confidence: 0.88 },
    { field: '乙方名称', value: '上海月明信息系统有限公司', confidence: 0.97 },
    { field: '签订日期', value: '2024-06-01', confidence: 0.92 },
    { field: '合同总金额', value: '¥850,000', confidence: 0.91 },
    { field: '付款条件', value: '签约30%，验收60%，质保金10%', confidence: 0.85 },
  ],
  rawText: '合同编号：HT-2024-DEMO\n甲方：示例甲方科技有限公司\n乙方：上海月明信息系统有限公司\n签订日期：2024年6月1日\n合同总金额：人民币捌拾伍万元整（¥850,000）\n付款条件：合同签订后3个工作日内支付30%...',
  sourceFile: 'contract_scan_001.jpg',
  extractedAt: daysAgo(0),
  reviewStatus: 'pending',
};

export const mockKnowledgeDocs: KnowledgeDoc[] = [
  {
    id: 'd1',
    title: '研发设计规范 v3.2',
    description: '统一研发设计输出规范，含流程图、接口文档模板',
    filename: 'design_spec_v3.2.md',
    fileType: 'md',
    size: 24500,
    folder: '研发规范',
    versions: [
      { version: '3.2', filename: 'design_spec_v3.2.md', size: 24500, updatedAt: daysAgo(10), author: '技术部', changelog: '新增微服务接口规范章节' },
      { version: '3.1', filename: 'design_spec_v3.1.md', size: 23100, updatedAt: daysAgo(30), author: '技术部', changelog: '更新数据库设计规范' },
      { version: '3.0', filename: 'design_spec_v3.0.md', size: 21000, updatedAt: daysAgo(60), author: '架构组', changelog: '首次发布设计规范文档' },
    ],
    tags: ['研发', '规范', '设计'],
    summary: '本文档定义了公司在产品研发过程中的设计输出规范，包括流程图绘制标准、接口文档模板、数据库设计准则等。',
    linkedSoftware: 'PLM-v2.3',
    permissions: { roles: ['admin', 'manager', 'user'], public: true },
    createdAt: daysAgo(60),
    updatedAt: daysAgo(10),
  },
  {
    id: 'd2',
    title: '方案评审规则手册',
    description: '方案评审流程、评分标准、常见问题与建议',
    filename: 'review_rules.md',
    fileType: 'md',
    size: 18200,
    folder: '评审规则',
    versions: [
      { version: '2.1', filename: 'review_rules.md', size: 18200, updatedAt: daysAgo(15), author: '质量部', changelog: '增加AI辅助评审说明' },
      { version: '2.0', filename: 'review_rules.md', size: 16800, updatedAt: daysAgo(45), author: '质量部', changelog: '重构评审流程' },
    ],
    tags: ['评审', '流程', '质量'],
    summary: '本手册详细说明了内部技术方案评审的完整流程、评分维度（技术可行性、成本、风险、进度）、评审委员会组成及常见问题处理建议。',
    linkedSoftware: '',
    permissions: { roles: ['admin', 'manager'], public: false },
    createdAt: daysAgo(45),
    updatedAt: daysAgo(15),
  },
  {
    id: 'd3',
    title: '系统集成技术白皮书',
    description: '第三方系统集成方案、接口标准、安全要求',
    filename: 'integration_wp.pdf',
    fileType: 'pdf',
    size: 560000,
    folder: '技术方案',
    versions: [
      { version: '1.0', filename: 'integration_wp.pdf', size: 560000, updatedAt: daysAgo(20), author: '架构组', changelog: '初始发布' },
    ],
    tags: ['集成', '架构', '接口'],
    summary: '详细阐述了与金蝶、用友等主流OA/ERP系统的集成技术方案，包括鉴权机制、字段映射、数据同步策略与安全合规要求。',
    linkedSoftware: 'OA-Connector-v1.0',
    permissions: { roles: ['admin', 'manager'], public: false },
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
];

export const mockCodeScanResults: CodeScanResult[] = [
  {
    id: 'cs-1',
    scanId: 'scan-001',
    contractCode: 'HT-2024-001',
    apiKey: 'sk-proj-****-a1b2',
    triggeredAt: daysAgo(1) + 'T10:30:00',
    issues: [
      { id: 'i1', severity: 'warning', type: '性能', message: '接口响应时间超过阈值（平均 2.3s > 1.5s）', file: 'api/user.ts', line: 45, suggestion: '建议添加缓存层或优化数据库查询' },
      { id: 'i2', severity: 'info', type: '规范', message: '函数命名不符合驼峰规范', file: 'utils/helper.ts', line: 12, suggestion: '将 formatDate 改为 formatDateCamelCase 风格一致' },
    ],
    status: 'completed',
  },
  {
    id: 'cs-2',
    scanId: 'scan-002',
    contractCode: 'HT-2024-002',
    apiKey: 'sk-proj-****-c3d4',
    triggeredAt: daysAgo(2) + 'T14:00:00',
    issues: [
      { id: 'i3', severity: 'error', type: '安全', message: '发现硬编码 API Key', file: 'config/env.ts', line: 8, suggestion: '请将敏感信息移至环境变量或密钥管理系统' },
      { id: 'i4', severity: 'warning', type: '依赖', message: '依赖包存在已知 CVE 漏洞', file: 'package.json', line: 22, suggestion: '建议升级 lodash 至 4.17.21+' },
    ],
    status: 'completed',
  },
];

export const mockTestCases: TestCase[] = [
  { id: 'tc-1', title: '用户登录接口单元测试', contractCode: 'HT-2024-001', type: 'unit', status: 'passed', coverage: 95, createdAt: daysAgo(5) },
  { id: 'tc-2', title: '数据同步集成测试', contractCode: 'HT-2024-001', type: 'integration', status: 'passed', coverage: 82, createdAt: daysAgo(4) },
  { id: 'tc-3', title: '合同信息提取验收测试', contractCode: 'HT-2024-002', type: 'acceptance', status: 'pending', coverage: 0, createdAt: daysAgo(3) },
  { id: 'tc-4', title: '权限控制单元测试', contractCode: 'HT-2024-003', type: 'unit', status: 'failed', coverage: 78, createdAt: daysAgo(2) },
];

export const mockOASyncConfigs: OASyncConfig[] = [
  {
    id: 'oa-1',
    platform: 'yonyou',
    enabled: true,
    syncType: 'daily',
    endpoint: 'https://api.yonyoucloud.com/v1/enterprise/sync',
    apiKey: 'yonyou-key-****-demo',
    apiSecret: '****',
    fieldMappings: [
      { localField: 'contract.code', remoteField: 'contract_no', transform: 'uppercase' },
      { localField: 'contract.amount', remoteField: 'total_amount', transform: 'number' },
      { localField: 'contract.partyA', remoteField: 'customer_name' },
    ],
    lastSyncAt: daysAgo(1) + 'T02:00:00',
    lastSyncStatus: 'success',
  },
];

export const getDashboardStats = (): DashboardStats => {
  const contracts = mockContracts;
  return {
    totalContracts: contracts.length,
    activeContracts: contracts.filter(c => c.status === 'active').length,
    riskContracts: contracts.filter(c => c.status === 'risk').length,
    expiringSoonContracts: contracts.filter(c => {
      const diff = (new Date(c.expireDate).getTime() - new Date().getTime()) / 86400000;
      return diff > 0 && diff < 60 && c.status !== 'completed';
    }).length,
    thisMonthContracts: contracts.filter(c => {
      const d = new Date(c.createdAt);
      const n = new Date();
      return d.getMonth() === n.getMonth() && d.getFullYear() === n.getFullYear();
    }).length,
    pendingReviews: 3,
  };
};
